name: Git Checks

on: [push]

jobs:
  block-fixup:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@090d9c9d # Always pin
    - name: Block Fixup Merge
      uses: 13rac1/block-fixup-merge-action@master
