name: Git Checks

on: [push]

jobs:
  block-fixup:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2.0.0 # Always pin
    - name: Block Fixup/Squash Merge
      uses: 13rac1/block-fixup-merge-action@master
